<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ProcessCodeAdapter" nsURI="platform:/plugin/ProcessCodeAdapter/model/ProcessCodeAdapter.ecore"
    nsPrefix="ProcessCodeAdapter">
  <eClassifiers xsi:type="ecore:EClass" name="NodeToImport" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/plugin/ProcessDefinition/model/ProcessDefinition.ecore#//Import"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FolderToSystem" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/plugin/ProcessDefinition/model/ProcessDefinition.ecore#//SystemModule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileToTask" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/plugin/MocaTree/model/MocaTree.ecore#//File"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/plugin/ProcessDefinition/model/ProcessDefinition.ecore#//Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeToInvocation" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/plugin/MocaTree/model/MocaTree.ecore#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/plugin/ProcessDefinition/model/ProcessDefinition.ecore#//Invocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FolderToModule" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractCorrespondence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass platform:/plugin/MocaTree/model/MocaTree.ecore#//Folder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass platform:/plugin/ProcessDefinition/model/ProcessDefinition.ecore#//Module"/>
  </eClassifiers>
  <eSubpackages name="Rules" nsURI="platform:/plugin/ProcessCodeAdapter/model/ProcessCodeAdapter.ecore#//Rules"
      nsPrefix="Rules">
    <eClassifiers xsi:type="ecore:EClass" name="NodeToInvocationRecursiveRule" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="NodeToInvocationDifferentModuleRule"
        eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="NodeToImportRule" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="NodeToInvocationRule" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="SubFolderToModuleRule" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractNodeToInvocationRule" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="RootToSystemRule" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="FileToTaskRule" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractOtherInvokedTaskRule" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractNodeToImportRule" eSuperTypes="platform:/plugin/org.moflon.tgg.runtime/model/Runtime.ecore#//AbstractRule"/>
  </eSubpackages>
</ecore:EPackage>
